server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: user-service-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: user-service
          __path__: /var/log/user-service/application.log

  - job_name: product-service-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: product-service
          __path__: /var/log/product-service/application.log

  - job_name: order-service-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: order-service
          __path__: /var/log/orderservice/application.log
